;;; package.el --- Package metadata for markdown-mermaid
;; no-byte-compile: t

;; Author: Daniel Vianna <dmlvianna@gmail.com>
;; Version: 0.1.1
;; Package-Requires: ((emacs "26.1") (markdown-mode "2.3"))
;; Keywords: markdown, tools, mermaid, diagrams
;; URL: https://github.com/pasunboneleve/markdown-mermaid

;;; Commentary:

;; This file is automatically generated by the package system.
;; DO NOT EDIT!

(define-package 'markdown-mermaid
  "Preview Mermaid diagrams within Markdown buffers."
  :version "0.1.1"
  :summary "Preview Mermaid diagrams within Markdown buffers."
  :description
  "This package extracts mermaid code blocks from markdown buffers, compiles
them using the mermaid-cli (mmdc), and displays the resulting image in
a new buffer.

It automatically attempts to match the generated diagram colors to your
current Emacs theme variables.

Requirements:
  npm install -g @mermaid-js/mermaid-cli"
  :keywords '(markdown tools mermaid diagrams)
  :url "https://github.com/pasunboneleve/markdown-mermaid")

;;; package.el ends here
